title: "Termux Games"
description: "This is a simple tools for played games in Termux App ðŸŽ®"
theme: jekyll-theme-tactile
baseurl: ""
url: "https://fajarkim.github.io"
markdown: kramdown
include:
  - README.md
